name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (Skip Tests)
        run: mvn clean package -DskipTests

      - name: Update dependency graph
        if: github.event_name == 'push'
        uses: advanced-security/maven-dependency-submission-action@v1
        with:
          directory: .
